### ISSUE TITLE
Infinite Heal/Reach - Powerplay/Weapon mixup

### ISSUE THREAD

**Issue by NooctisUGC** [Phil25/RTD#109]
# Bug description

infinite heal reach / without holding medigun - Weapon Mixup, Powerplay

Heal, Roll mixup, Switch to ubersaw causes you to have infinite heal reach and can heal players without using the medigun. Video provided.

Powerplay has the same issue. Heal, Powerplay, Switch to ubersaw. These were discovered on accident. Video provided

I understand these may not be as common due to needing to role the perks why healing and all. but worthy to be noticed incase you can fix

# Report checks

> ### Please describe the bug in the section above, then post it and tick the correct boxes below.

### Required
- [x] The bug does not have an open issue.
- [x] I have described the bug.
- [ ] I mentioned whether the bug is sporadic or systematic.

### Optional
- [x] Steps to reproduce the bug are known and have been described.
- [ ] I have access to server error logs and have provided them, if any.
- [ ] I am able to check the RTD version (`sm_cvar sm_rtd2_version`) and have specified it.
- [ ] I have access to RTD default configuration file (`rtd2_perks.default.cfg`) and can confirm it's the one bundled with plugin release archive.
- [ ] I have access to RTD custom configuration file (`rtd2_perks.custom.cfg` or other) and have attached it to this issue.
- [ ] The issue is related to a particular perk, which has been specified by a label.

https://github.com/Phil25/RTD/assets/165837017/e9857c5a-480a-4b4a-8c8a-c42339ac5f59

https://github.com/Phil25/RTD/assets/165837017/f5a77a28-d8ca-4612-a59c-d5a5f51e32bd

**Comment by Phil25** [comment]
Thanks for the report, looks like the healing beam isn't broken during forced weapon changes.

**Comment by NooctisUGC** [comment]
Fast Weapon Switching off, Causes the RTD to become a little broken. Most likely a TF2 issue much rather then the RTD itself but thought I'd let you know @Phil25 

![image](https://github.com/Phil25/RTD/assets/165837017/5dea71a3-6742-4466-a8ea-0314f441191b)

https://github.com/Phil25/RTD/assets/165837017/b4bda03c-24fe-49e6-b153-35cae26d7810

**Comment by Phil25** [comment]
Fixed in [2.5.5](https://github.com/Phil25/RTD/releases/tag/2.5.5).

Disabling fast weapon switch is a bit unfortunate to this perk. But I couldn't find a way to address it easily...
