### ISSUE TITLE
Kill binding while frozen respawns you with 0 hp.

### ISSUE THREAD

**Issue by Lenny-the-burger** [Phil25/RTD#111]
# Bug description

Rolling frozen and then killbinding while still frozen respawns you with zero hp.

# Report checks

> ### Please describe the bug in the section above, then post it and tick the correct boxes below.

### Required
- [x] The bug does not have an open issue.
- [x] I have described the bug.
- [x] I mentioned whether the bug is sporadic or systematic.

### Optional
- [x] Steps to reproduce the bug are known and have been described.
- [ ] I have access to server error logs and have provided them, if any.
- [ ] I am able to check the RTD version (`sm_cvar sm_rtd2_version`) and have specified it.
- [ ] I have access to RTD default configuration file (`rtd2_perks.default.cfg`) and can confirm it's the one bundled with plugin release archive.
- [ ] I have access to RTD custom configuration file (`rtd2_perks.custom.cfg` or other) and have attached it to this issue.
- [x] The issue is related to a particular perk, which has been specified by a label.

**Comment by Phil25** [comment]
Fixed in [2.5.5](https://github.com/Phil25/RTD/releases/tag/2.5.5).
