### ISSUE TITLE
Explode RTD can placed outside of a wall if unlucky

### ISSUE THREAD

**Issue by NooctisUGC** [Phil25/RTD#112]
Explode RTD can placed outside of a wall if unlucky which causes to to hang not able to do anything.

Not a big issue but was reported here - https://www.ugc-gaming.net/index.php?threads/katyushaa-reporting-bug-team-fortress-2.3802/

I was unable to re-create this but it does look like you might be able to get unlucky and butcher the RTD bomb spawn.
But to re-create this it looks like you'd have to be in a small area (Image was in 2fort blu sewers)

Image by reporter
![Screenshot (839)](https://github.com/Phil25/RTD/assets/165837017/2073cd4f-6f4b-4718-ae8b-a1e3a932fad9)

# Report checks

> ### Please describe the bug in the section above, then post it and tick the correct boxes below.

### Required
- [x] The bug does not have an open issue.
- [x] I have described the bug.
- [x] I mentioned whether the bug is sporadic or systematic.

### Optional
- [x] Steps to reproduce the bug are known and have been described.
- [ ] I have access to server error logs and have provided them, if any.
- [ ] I am able to check the RTD version (`sm_cvar sm_rtd2_version`) and have specified it.
- [ ] I have access to RTD default configuration file (`rtd2_perks.default.cfg`) and can confirm it's the one bundled with plugin release archive.
- [ ] I have access to RTD custom configuration file (`rtd2_perks.custom.cfg` or other) and have attached it to this issue.
- [ ] The issue is related to a particular perk, which has been specified by a label.

**Comment by Phil25** [comment]
This is kinda a similar issue when the bomb spawns right as you jump off a roof, then being to dangle underneath unable to see it. It's not intentional but I was aware of the issue, and honestly I'm willing to chalk it up to bad luck since I'm not sure how to address it.

Feel free to reopen if you disagree.
