### ISSUE TITLE
Exception reported: Invalid Handle e8500cec (error 3)

### ISSUE THREAD

**Issue by naydef** [Phil25/RTD#118]
# Bug description
The following errors seem to get spammed in error logs for reason unknown.

```
L 05/18/2024 - 11:51:19: [SM] Exception reported: Invalid Handle e8500cec (error 3)
L 05/18/2024 - 11:51:19: [SM] Blaming: Gameplay\RTD\rtd.smx
L 05/18/2024 - 11:51:19: [SM] Call stack trace:
L 05/18/2024 - 11:51:19: [SM]   [0] StringMap.GetValue
L 05/18/2024 - 11:51:19: [SM]   [1] Line 195, rtd/classes/perk.sp::Perk.External.get
L 05/18/2024 - 11:51:19: [SM]   [2] Line 1331, Gameplay/RTD/rtd.sp::ManagePerk
L 05/18/2024 - 11:51:19: [SM]   [3] Line 1490, Gameplay/RTD/rtd.sp::RemovePerk
L 05/18/2024 - 11:51:19: [SM]   [4] Line 218, Gameplay/RTD/rtd.sp::ResetAllClients
L 05/18/2024 - 11:51:19: [SM]   [5] Line 769, Gameplay/RTD/rtd.sp::Event_RoundStart
L 05/18/2024 - 11:54:54: [SM] Exception reported: Invalid Handle e8500cec (error 3)
L 05/18/2024 - 11:54:54: [SM] Blaming: Gameplay\RTD\rtd.smx
L 05/18/2024 - 11:54:54: [SM] Call stack trace:
L 05/18/2024 - 11:54:54: [SM]   [0] StringMap.GetValue
L 05/18/2024 - 11:54:54: [SM]   [1] Line 195, rtd/classes/perk.sp::Perk.External.get
L 05/18/2024 - 11:54:54: [SM]   [2] Line 1331, Gameplay/RTD/rtd.sp::ManagePerk
L 05/18/2024 - 11:54:54: [SM]   [3] Line 1490, Gameplay/RTD/rtd.sp::RemovePerk
L 05/18/2024 - 11:54:54: [SM]   [4] Line 218, Gameplay/RTD/rtd.sp::ResetAllClients
L 05/18/2024 - 11:54:54: [SM]   [5] Line 769, Gameplay/RTD/rtd.sp::Event_RoundStart
L 05/18/2024 - 11:55:04: [SM] Exception reported: Invalid Handle e8500cec (error 3)
L 05/18/2024 - 11:55:04: [SM] Blaming: Gameplay\RTD\rtd.smx
L 05/18/2024 - 11:55:04: [SM] Call stack trace:
L 05/18/2024 - 11:55:04: [SM]   [0] StringMap.GetValue
L 05/18/2024 - 11:55:04: [SM]   [1] Line 195, rtd/classes/perk.sp::Perk.External.get
L 05/18/2024 - 11:55:04: [SM]   [2] Line 1331, Gameplay/RTD/rtd.sp::ManagePerk
L 05/18/2024 - 11:55:04: [SM]   [3] Line 1490, Gameplay/RTD/rtd.sp::RemovePerk
L 05/18/2024 - 11:55:04: [SM]   [4] Line 218, Gameplay/RTD/rtd.sp::ResetAllClients
L 05/18/2024 - 11:55:04: [SM]   [5] Line 769, Gameplay/RTD/rtd.sp::Event_RoundStart
```
Version 2.5.3

### Required
- [ ] The bug does not have an open issue.
- [x] I have described the bug.
- [x] I mentioned whether the bug is sporadic or systematic.

### Optional
- [ ] Steps to reproduce the bug are known and have been described.
- [x] I have access to server error logs and have provided them, if any.
- [x] I am able to check the RTD version (`sm_cvar sm_rtd2_version`) and have specified it.
- [x] I have access to RTD default configuration file (`rtd2_perks.default.cfg`) and can confirm it's the one bundled with plugin release archive.
- [ ] I have access to RTD custom configuration file (`rtd2_perks.custom.cfg` or other) and have attached it to this issue.
- [ ] The issue is related to a particular perk, which has been specified by a label.

**Comment by Phil25** [comment]
Do you have any custom perks going?

**Comment by naydef** [comment]
Yes, we have custom perks, however I'm not sure if this was caused by custom perk being active.

**Comment by Phil25** [comment]
I’m just wondering since there’s a bit of specifics when using external perks. That’s not to say that RTD should break this way however things are done via the API, but maybe there’s something to help me track this down.

Having said that, I haven’t looked into this issue myself yet.

**Comment by naydef** [comment]
I haven't seen this error show up for some time now.

I'll close this for now, might reopen if I see this again.
