### ISSUE TITLE
Split distribution of translation files

### ISSUE THREAD

**Issue by Phil25** [Phil25/RTD#20]
https://wiki.alliedmods.net/Translations_(SourceMod_Scripting)#Distributing_Language_Files

**Comment by deluxghost** [comment]
and choose client's language rather than server language? players speak different languages

**Comment by Phil25** [comment]
I chose server language because the original RTD also uses it. It's not in a priority to change, neither is this issue.

**Comment by deluxghost** [comment]
yes, that's just a note, as well as translatable perks name

**Comment by Phil25** [comment]
With translations moved to Crowdin, the translations are easier to be generated in a single file, which is done by a Python script. As such, closing this as `wontdo`.
