### ISSUE TITLE
sm_rtd2_disabled doesn't work properly

### ISSUE THREAD

**Issue by MAGNAT2645** [Phil25/RTD#27]
I've put sm_rtd2_disabled "noclip" and plugin said that Noclip perk is disabled but players can roll it.

**Comment by LeoNardoProGame** [comment]
1) Error in line 1562. Says need to put (int &client).
2) And the second error is (rtd2.phrases and rtd 2_perks.phrases). Doesn't want to translate!!!

**Comment by Phil25** [comment]
Are you sure it said that `Noclip` is disabled? Keep in mind it should say `Flying` instead, as that's the name of the perk.

Also, I can't see this mentioned anywhere (weirdly enough, not even in [Updating from before 2.0.0](https://github.com/Phil25/RTD/wiki/updating-from-before-v2.0.0)) but unique perk tags are not used to address perks anymore when parsing disabled perks. So as of now, putting `noclip` (which is a unique tag, not the token (which is `flying`)) should not disable the perk.

You should use `flying` or its ID, `4`, to disable the perk, or set the its `mode` setting to `0` to disable clipping through walls.

Not having this is a bad design decision on my part, I could try adding a mean to address perks by a unique tag, but it's very difficult finding time :/

@LeoNardoProGame I don't know what you mean but it sounds like you might want to open another issue.

**Comment by MAGNAT2645** [comment]
Yeah, i've fixed that a few months ago.

**Comment by Phil25** [comment]
Yeah lol, it was more of an occasion to discuss whether making unique tags work is worthwhile implementing.
