### ISSUE TITLE
Fast Hands Attribute Change

### ISSUE THREAD

**Issue by kking117** [Phil25/RTD#29]
The Fast Hands roll uses attributes 6 and 97 for increased fire rate and reload speed respectively. The issue is that they override the weapon's same attributes and then remove them completely when the roll is up (any from of loadout regeneration fixes this). While not completely game breaking it can be bad in say MvM as it would replace the fire rate and reload speed upgrades on your weapons. I know this is an issue that can't be fully fixed but may I suggest using attributes 549 and 548 instead, these attributes are only used in the vanilla game for the minify spell and are only applied to the player, not the weapons so it wouldn't interfere with weapon fire rate and reload speeds attributes in normal gameplay.

**Comment by Phil25** [comment]
I am very certain it wouldn't remove the weapon's base attributes, as I remember testing whether this could be a problem. That being said, I haven't tested MvM.

Thank you for pointing out the other two attributes, decoupling the dependency from often-used game features is always beneficial. This will also simplify the perk greatly.

**Comment by Phil25** [comment]
Welp, I had no luck using the attributes you provided (got some weird results when combined them). But I searched some different, less used ones.
