### ISSUE TITLE
Pumpkin Trail Log Errors

### ISSUE THREAD

**Issue by Psykotikism** [Phil25/RTD#30]
L 08/27/2019 - 20:44:28: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 08/27/2019 - 20:44:28: [SM] Blaming: rtd.smx
L 08/27/2019 - 20:44:28: [SM] Call stack trace:
L 08/27/2019 - 20:44:28: [SM]   [1] Line 60, rtd/cache.sp::GetFloatCache
L 08/27/2019 - 20:44:28: [SM]   [2] Line 144, rtd/perks/pumpkintrail.sp::PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM]   [3] Line 134, rtd/perks/pumpkintrail.sp::Timer_PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 08/27/2019 - 20:44:28: [SM] Blaming: rtd.smx
L 08/27/2019 - 20:44:28: [SM] Call stack trace:
L 08/27/2019 - 20:44:28: [SM]   [1] Line 60, rtd/cache.sp::GetFloatCache
L 08/27/2019 - 20:44:28: [SM]   [2] Line 144, rtd/perks/pumpkintrail.sp::PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM]   [3] Line 134, rtd/perks/pumpkintrail.sp::Timer_PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 08/27/2019 - 20:44:28: [SM] Blaming: rtd.smx
L 08/27/2019 - 20:44:28: [SM] Call stack trace:
L 08/27/2019 - 20:44:28: [SM]   [1] Line 60, rtd/cache.sp::GetFloatCache
L 08/27/2019 - 20:44:28: [SM]   [2] Line 144, rtd/perks/pumpkintrail.sp::PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM]   [3] Line 134, rtd/perks/pumpkintrail.sp::Timer_PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 08/27/2019 - 20:44:28: [SM] Blaming: rtd.smx
L 08/27/2019 - 20:44:28: [SM] Call stack trace:
L 08/27/2019 - 20:44:28: [SM]   [1] Line 60, rtd/cache.sp::GetFloatCache
L 08/27/2019 - 20:44:28: [SM]   [2] Line 144, rtd/perks/pumpkintrail.sp::PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM]   [3] Line 134, rtd/perks/pumpkintrail.sp::Timer_PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 08/27/2019 - 20:44:28: [SM] Blaming: rtd.smx
L 08/27/2019 - 20:44:28: [SM] Call stack trace:
L 08/27/2019 - 20:44:28: [SM]   [1] Line 60, rtd/cache.sp::GetFloatCache
L 08/27/2019 - 20:44:28: [SM]   [2] Line 144, rtd/perks/pumpkintrail.sp::PumpkinTrail_Detonate
L 08/27/2019 - 20:44:28: [SM]   [3] Line 134, rtd/perks/pumpkintrail.sp::Timer_PumpkinTrail_Detonate

**Comment by Phil25** [comment]
Weird, something must be changing `m_hOwnerEntity` in the second after a pumpkin spawns. Or it's being set incorrectly from the start. No steps for reproduction? Are you using any interesting plugins? Does it happen often?

**Comment by Phil25** [comment]
Can't repro, any more info on this?

**Comment by Psykotikism** [comment]
It's been 2+ years. I could never figure out how to reproduce the error so I'm convinced this was caused by a conflicting plugin.
