### ISSUE TITLE
[Feature Request] Use client's language instead of server's language when showing translations

### ISSUE THREAD

**Issue by Tiagoquix** [Phil25/RTD#44]
I see that this plugin uses the [server language (LANG_SERVER)](https://github.com/Phil25/RTD/blob/master/scripting/rtd.sp#L982) instead of a function like [this](https://github.com/50DKP/FF2-Official/blob/experimental/addons/sourcemod/scripting/freak_fortress_2.sp#L7416). What the LANG_SERVER does is basically use [this setting](https://github.com/alliedmodders/sourcemod/blob/master/configs/core.cfg#L30) instead of using the client's language.

Can you change the plugin in a way that it shows the translated phrases based on the client's language and not on the server language? This is what most plugins do.

Thanks in advance.

**Comment by Tiagoquix** [comment]
There is even an option in the core.cfg file that is related to my issue.

https://github.com/alliedmodders/sourcemod/blob/master/configs/core.cfg#L76

```
	/**
	 * Enables or disables whether SourceMod reads a client's cl_language cvar to set 
	 * their language for server-side phrase translation.
	 *
	 * "on"		- Translate using the client's language (default)
	 * "off"	- Translate using default server's language
	 */
	"AllowClLanguageVar"		"On"
```

**Comment by MAGNAT2645** [comment]
@Phil25, just replace `LANG_SERVER` with client index, that's all :smiley:

**Comment by Phil25** [comment]
> @Phil25 Would it also be possible to have the effects' names be translatable per language as well?

I've taken a brief look at it per #49 and translating perk names comes with a unique set of challenges. I haven't come to a conclusion yet but I doubt I will support it.
