### ISSUE TITLE
new syntax

### ISSUE THREAD

**Issue by dedimark** [Phil25/RTD#50]
Can anyone update plugin,

problems with Sourcemod - 1.11 compile

**Comment by Phil25** [comment]
Can you post the warning/error messages?

**Comment by dedimark** [comment]
Sourcemod - 1.11 build 6917

//// rtd.sp
//
// rtd\classes\containers.sp(159) : error 077: arrays cannot be indexed by non-integral type 'bool'
//
// 1 Error.
//
// Compilation Time: 0.98 sec

**Comment by Phil25** [comment]
Fixed in 4fc1b27120cf50134b6d34ba4c1fe86a85e9dae7
