### ISSUE TITLE
Add stocks to include for use by external perk addition modules

### ISSUE THREAD

**Issue by flleeppyy** [Phil25/RTD#54]
I'm writing some perks for a server and I find myself copying a bunch of functions from RTD2 in stocks.sp, and it would be nice if they were added to rtd2.inc so there isn't a bunch of duplicate code.
I could make a PR for it but I'm afraid I wouldn't do a very good job.

**Comment by Phil25** [comment]
The problem with this is that exposing those functions means I'll have to support them (check client validity, make sure everything is configurable nicely) and I don't want to do that...
