### ISSUE TITLE
Incline Problem Bug

### ISSUE THREAD

**Issue by fearts** [Phil25/RTD#7]
If you roll Incline Problem it doesn't go away after the set time. The only way to make it stop is by dying or the round ending.

Here is my config for this perk.

	"55"	//Makes it difficult to go up inclines
	{
		"name"			"Incline Problem"
		"good"			"0"
		"sound"			"vo/spy_dominationheavy02.mp3"
		"token"			"inclineproblem"
		"time"			"0"
		"class"			"0"
		"weapons"		"0"
		"tags"			"inclineproblem, incline, slope, problem, stair, stairs, climbing, step, steps, bad"
		"call"			"InclineProblem_Call"
	}

**Comment by Phil25** [comment]
This was reported on the forum and already fixed. Have you downloaded the plugin again? (Version number didn’t change).

**Comment by fearts** [comment]
Update fixes it. Sorry didn't read the change log.
