### ISSUE TITLE
"Powerplay" 99% resistance to everything is kept if you switch classes while at spawn right after rolling it

### ISSUE THREAD

**Issue by Th3F4ult** [Phil25/RTD#83]
It persists through deaths, team changes and going into spectator mode.

I have no logs since I was just playing in a server with RTD 2.4.0.

**Comment by Phil25** [comment]
Thanks for repro steps. This is most likely the same issue as #79 but I’ll keep it open just in case it’s something per perk.

I’ll start investigation tomorrow (back from vacation) and roll out a fix asap.

**Comment by Phil25** [comment]
I've confirmed this is the same issue. I'm closing it as a duplicate of #79 to direct the discussion there.
