### ISSUE TITLE
PowePlay Causing Taunt Issues

### ISSUE THREAD

**Issue by fearts** [Phil25/RTD#9]
TF2_SetPlayerPowerPlay causes a issue that if certain conditions are met it causes TFCond_Taunting to not fire properly.

On my FF2 server I use the TauntCrits plugin that gives crits to a player for a time after they finish taunting. I was made aware of a issue were players reported to me after they rolled PowerPlay they could no longer get Taunt Crits unless they rejoined the server or the map changed. After much testing I was able to recreate the problem.

1. Taunt with any taunt that lets you stay taunted like high five.
2. While in the taunt roll PowerPlay.
3. Immediately stop taunting while in PowePlay.

Doing the above 3 steps will cause seemingly any function that looks at TFCond_Taunting to not fire.

This problem only happens if TF2_SetPlayerPowerPlay is present. If I remove this line:

		TF2_SetPlayerPowerPlay(client, true);

Then it works perfectly fine. Something in PowerPlay itself is causing it.

Solution:

We edited PowerPlay so when it is rolled before it gives any perks it will remove TFCond_Taunting from the player, causing them to stop taunting, then 0.1 seconds later gives the PowerPlay perks. I hope this edit might be able to be added to the official version or at least given a CVAR to toggle this on for people who are having issues like myself. Thanks.
[powerplay.zip](https://github.com/Phil25/RTD/files/2431272/powerplay.zip)

**Comment by Phil25** [comment]
Thank you, I'll implement this in the release version.
