### ISSUE TITLE
"override class restriction" argument for ForceRTD does not seem to provide much value

### ISSUE THREAD

**Issue by Tiagoquix** [Phil25/RTD#90]
# Bug description

When using `sm_forcertd`, whetever I specify "`override class restriction`" or not the effect will always be applied regardless of my class. From my point of view, there is no need to have it in `sm_forcertd` — you would know if you applied a non-intended effect for your class via admin commands.

This is always reproducible, so this is systematic.

RTD version: 2.4.0

# Report checks

> ### Please describe the bug in the section above, then post it and tick the correct boxes below.

### Required
- [x] The bug does not have an open issue.
- [x] I have described the bug.
- [x] I mentioned whether the bug is sporadic or systematic.

### Optional
- [x] Steps to reproduce the bug are known and have been described.
- [ ] I have access to server error logs and have provided them, if any.
- [x] I am able to check the RTD version (`sm_cvar sm_rtd2_version`) and have specified it.
- [x] I have access to RTD default configuration file (`rtd2_perks.default.cfg`) and can confirm it's the one bundled with plugin release archive.
- [ ] I have access to RTD custom configuration file (`rtd2_perks.custom.cfg`) and have attached it to this issue. **-- NO CUSTOM CONFIGS PRESENT**
- [ ] The issue is related to a particular perk, which has been specified by a label.

**Comment by Phil25** [comment]
I agree, even forgot this existed lol

**Comment by Phil25** [comment]
I was randomly browsing old changelog and it looks like this argument has been removed all the way back in 2018. The command description has been outdated since then.
