### ISSUE TITLE
Clarify Firework damage in docs

### ISSUE THREAD

**Issue by Tiagoquix** [Phil25/RTD#95]
https://github.com/Phil25/RTD/wiki/perk-list#-firework-

Maybe it should be clarified that the damage isn't the ignite damage but a separate damage from the effect itself?

**Comment by Phil25** [comment]
What do you suggest? `ignite` and `damage` are separate options completely.

**Comment by Phil25** [comment]
Still not sure I understand, ignite doesn't deal any damage whatsoever, the afterburn does.

Here are my suggestions to hopefully clarify some things:
#### `damage`
```diff
- "-1"		"Explode the player."
- "0"		"Deal no damage."
- "<integer>"	"Deal a custom damage value."
+ "-1"		"Explode the player in air, killing them regardless of health."
+ "0"		"No explosion happens and no damage is dealt. Ignite works irrespectively of this setting."
+ "<integer>"	"Deal a custom damage value with an explosion."
```
#### `ignite`
```diff
- "1"	"Ignite the player."
+ "1"	"Ignite the player. Has no effect if the player died."
```
